version: "2"
services:
  mongodb:
    image: mongo
    volumes:
      - triton_db:/data/db
    restart: always

  server:
    depends_on:
      - mongodb
    build: 
      context: .
      args:
        - "PORT=${INTERNAL_DOCKER_PORT}"
    ports:
      - "${EXTERNAL_HOST_PORT}:${INTERNAL_DOCKER_PORT}"
    links:
      - mongodb
    environment:
      - "PORT=${INTERNAL_DOCKER_PORT}"
    volumes:
      - triton_logs:/app/log
    restart: always


volumes:
  triton_db:
  triton_logs:
